let tailwind;
try {
	tailwind = require("tailwindcss");
} catch (_) {
	tailwind = window.tailwind || {};
}

const plugin = tailwind.plugin;

tailwind.config = {
	darkMode: ['class', '[data-theme="dark"]'],
	theme: {
		extend: {
			colors: {
				"1": "hsl(var(--bg1) / <alpha-value>)",
				"2": "hsl(var(--bg2) / <alpha-value>)",
				"3": "hsl(var(--bg3) / <alpha-value>)",
				"a": "hsl(var(--a) / <alpha-value>)",
				"a-hover": "hsl(var(--a-hover) / <alpha-value>)",
				"a-decoration": "hsl(var(--a-decoration-color) / <alpha-value>)",
				"a-decoration-hover": "hsl(var(--a-decoration-color-hover) / <alpha-value>)",
				"bold": "hsl(var(--bold) / <alpha-value>)",
				"backdrop": "hsl(var(--backdrop) / <alpha-value>)",
				"bullet": "hsl(var(--bullet) / <alpha-value>)",
				"button": "hsl(var(--button) / <alpha-value>)",
				"button-hover": "hsl(var(--button-hover) / <alpha-value>)",
				"button-focus": "hsl(var(--button-focus) / <alpha-value>)",
				"button-inverse": "hsl(var(--button-inverse) / <alpha-value>)",
				"button-inverse-hover": "hsl(var(--button-inverse-hover) / <alpha-value>)",
				"button-inverse-focus": "hsl(var(--button-inverse-focus) / <alpha-value>)",
				"button-border": "hsl(var(--button-border) / <alpha-value>)",
				"button-border-hover": "hsl(var(--button-border-hover) / <alpha-value>)",
				"button-border-focus": "hsl(var(--button-border-focus) / <alpha-value>)",
				"callout-bg": "hsl(var(--callout-bg) / <alpha-value>)",
				"callout-border": "hsl(var(--callout-border) / <alpha-value>)",
				"callout-text": "hsl(var(--callout-text) / <alpha-value>)",
				"caption": "hsl(var(--caption) / <alpha-value>)",
				"chip": "hsl(var(--chip) / <alpha-value>)",
				"chip-text": "hsl(var(--chip-text) / <alpha-value>)",
				"code-bg": "hsl(var(--code-bg) / <alpha-value>)",
				"code-border": "hsl(var(--code-border) / <alpha-value>)",
				"code-text": "hsl(var(--code-text) / <alpha-value>)",
				"contrast": "hsl(var(--contrast) / <alpha-value>)",
				"contrast-hover": "hsl(var(--contrast-hover) / <alpha-value>)",
				"contrast-focus": "hsl(var(--contrast-focus) / <alpha-value>)",
				"contrast-inverse": "hsl(var(--contrast-inverse) / <alpha-value>)",
				"contrast-inverse-hover": "hsl(var(--contrast-inverse-hover) / <alpha-value>)",
				"contrast-inverse-focus": "hsl(var(--contrast-inverse-focus) / <alpha-value>)",
				"contrast-text": "hsl(var(--contrast-text) / <alpha-value>)",
				"counter": "hsl(var(--counter) / <alpha-value>)",
				"danger": "hsl(var(--danger) / <alpha-value>)",
				"danger-hover": "hsl(var(--danger-hover) / <alpha-value>)",
				"danger-focus": "hsl(var(--danger-focus) / <alpha-value>)",
				"danger-inverse": "hsl(var(--danger-inverse) / <alpha-value>)",
				"danger-inverse-hover": "hsl(var(--danger-inverse-hover) / <alpha-value>)",
				"danger-inverse-focus": "hsl(var(--danger-inverse-focus) / <alpha-value>)",
				"danger-text": "hsl(var(--danger-text) / <alpha-value>)",
				"divider": "hsl(var(--divider) / <alpha-value>)",
				"dropdown": "hsl(var(--dropdown) / <alpha-value>)",
				"dropdown-border": "hsl(var(--dropdown-border) / <alpha-value>)",
				"dropdown-divider": "hsl(var(--dropdown-divider) / <alpha-value>)",
				"dropdown-option-hover": "hsl(var(--dropdown-option-hover) / <alpha-value>)",
				"dropdown-option-focus": "hsl(var(--dropdown-option-focus) / <alpha-value>)",
				"dropdown-option-group": "hsl(var(--dropdown-option-group) / <alpha-value>)",
				"dropdown-option-text": "hsl(var(--dropdown-option-text) / <alpha-value>)",
				"dropdown-option-text-hover": "hsl(var(--dropdown-option-text-hover) / <alpha-value>)",
				"dropdown-option-text-focus": "hsl(var(--dropdown-option-text-focus) / <alpha-value>)",
				"dropdown-option-trailing-symbol": "hsl(var(--dropdown-option-trailing-symbol) / <alpha-value>)",
				"focus-outline": "hsl(var(--focus-outline) / <alpha-value>)",
				"h1": "hsl(var(--h1) / <alpha-value>)",
				"h2": "hsl(var(--h2) / <alpha-value>)",
				"h3": "hsl(var(--h3) / <alpha-value>)",
				"h4": "hsl(var(--h4) / <alpha-value>)",
				"h5": "hsl(var(--h5) / <alpha-value>)",
				"h6": "hsl(var(--h6) / <alpha-value>)",
				"input": "hsl(var(--input) / <alpha-value>)",
				"input-border-hover": "hsl(var(--input-border-hover) / <alpha-value>)",
				"input-border-focus": "hsl(var(--input-border-focus) / <alpha-value>)",
				"input-hover": "hsl(var(--input-hover) / <alpha-value>)",
				"input-focus": "hsl(var(--input-focus) / <alpha-value>)",
				"input-placeholder": "hsl(var(--input-placeholder) / <alpha-value>)",
				"input-value": "hsl(var(--input-value) / <alpha-value>)",
				"kbd-bg": "hsl(var(--kbd-bg) / <alpha-value>)",
				"kbd-border": "hsl(var(--kbd-border) / <alpha-value>)",
				"kbd-text": "hsl(var(--kbd-text) / <alpha-value>)",
				"label": "hsl(var(--label) / <alpha-value>)",
				"link": "hsl(var(--link) / <alpha-value>)",
				"link-hover": "hsl(var(--link-hover) / <alpha-value>)",
				"link-decoration": "hsl(var(--link-decoration-color) / <alpha-value>)",
				"link-decoration-hover": "hsl(var(--link-decoration-color-hover) / <alpha-value>)",
				"link-footer": "hsl(var(--link-footer) / <alpha-value>)",
				"link-footer-hover": "hsl(var(--link-footer-hover) / <alpha-value>)",
				"link-footer-decoration": "hsl(var(--link-footer-decoration-color) / <alpha-value>)",
				"link-footer-decoration-hover": "hsl(var(--link-footer-decoration-color-hover) / <alpha-value>)",
				"link-header": "hsl(var(--link-header) / <alpha-value>)",
				"link-header-hover": "hsl(var(--link-header-hover) / <alpha-value>)",
				"link-header-decoration": "hsl(var(--link-header-decoration-color) / <alpha-value>)",
				"link-header-decoration-hover": "hsl(var(--link-header-decoration-color-hover) / <alpha-value>)",
				"modal": "hsl(var(--modal) / <alpha-value>)",
				"modal-divider": "hsl(var(--modal-divider) / <alpha-value>)",
				"p": "hsl(var(--p) / <alpha-value>)",
				"page": "hsl(var(--page) / <alpha-value>)",
				"pre-bg": "hsl(var(--pre-bg) / <alpha-value>)",
				"pre-border": "hsl(var(--pre-border) / <alpha-value>)",
				"pre-text": "hsl(var(--pre-text) / <alpha-value>)",
				"primary": "hsl(var(--primary) / <alpha-value>)",
				"primary-hover": "hsl(var(--primary-hover) / <alpha-value>)",
				"primary-focus": "hsl(var(--primary-focus) / <alpha-value>)",
				"primary-inverse": "hsl(var(--primary-inverse) / <alpha-value>)",
				"primary-inverse-hover": "hsl(var(--primary-inverse-hover) / <alpha-value>)",
				"primary-inverse-focus": "hsl(var(--primary-inverse-focus) / <alpha-value>)",
				"primary-text": "hsl(var(--primary-text) / <alpha-value>)",
				"quote": "hsl(var(--quote) / <alpha-value>)",
				"quote-border": "hsl(var(--quote-border) / <alpha-value>)",
				"secondary": "hsl(var(--secondary) / <alpha-value>)",
				"secondary-hover": "hsl(var(--secondary-hover) / <alpha-value>)",
				"secondary-focus": "hsl(var(--secondary-focus) / <alpha-value>)",
				"secondary-inverse": "hsl(var(--secondary-inverse) / <alpha-value>)",
				"secondary-inverse-hover": "hsl(var(--secondary-inverse-hover) / <alpha-value>)",
				"secondary-inverse-focus": "hsl(var(--secondary-inverse-focus) / <alpha-value>)",
				"secondary-text": "hsl(var(--secondary-text) / <alpha-value>)",
				"small": "hsl(var(--small) / <alpha-value>)",
				"switch-off": "hsl(var(--switch-off) / <alpha-value>)",
				"switch-off-hover": "hsl(var(--switch-off-hover) / <alpha-value>)",
				"switch-off-focus": "hsl(var(--switch-off-focus) / <alpha-value>)",
				"switch-on": "hsl(var(--switch-on) / <alpha-value>)",
				"switch-on-hover": "hsl(var(--switch-on-hover) / <alpha-value>)",
				"switch-on-focus": "hsl(var(--switch-on-focus) / <alpha-value>)",
				"switch-border": "hsl(var(--switch-border) / <alpha-value>)",
				"switch-border-hover": "hsl(var(--switch-border-hover) / <alpha-value>)",
				"switch-border-focus": "hsl(var(--switch-border-focus) / <alpha-value>)",
				"switch-marker-off": "hsl(var(--switch-marker-off) / <alpha-value>)",
				"switch-marker-off-hover": "hsl(var(--switch-marker-off-hover) / <alpha-value>)",
				"switch-marker-off-focus": "hsl(var(--switch-marker-off-focus) / <alpha-value>)",
				"switch-marker-on": "hsl(var(--switch-marker-on) / <alpha-value>)",
				"switch-marker-on-hover": "hsl(var(--switch-marker-on-hover) / <alpha-value>)",
				"switch-marker-on-focus": "hsl(var(--switch-marker-on-focus) / <alpha-value>)",
				"table": "hsl(var(--table))",
				"table-header-text": "hsl(var(--table-header-text))",
				"table-header-row": "hsl(var(--table-header-row))",
				"table-header-divider": "hsl(var(--table-header-divider))",
				"table-row-even": "hsl(var(--table-row-even))",
				"table-row-odd": "hsl(var(--table-row-odd))",
				"table-row-divider": "hsl(var(--table-row-divider))",
				"table-text": "hsl(var(--table-text))",
				"solid": "hsl(var(--text-solid) / <alpha-value>)",
				"solid-link": "hsl(var(--text-solid-link) / <alpha-value>)",
				"solid-link-hover": "hsl(var(--text-solid-link-hover) / <alpha-value>)",
				"soft": "hsl(var(--text-soft) / <alpha-value>)",
				"soft-link": "hsl(var(--text-soft-link) / <alpha-value>)",
				"soft-link-hover": "hsl(var(--text-soft-link-hover) / <alpha-value>)",
				"faint": "hsl(var(--text-faint) / <alpha-value>)",
				"faint-link": "hsl(var(--text-faint-link) / <alpha-value>)",
				"faint-link-hover": "hsl(var(--text-faint-link-hover) / <alpha-value>)",
				"tooltip": "hsl(var(--tooltip))",
			},
			spacing: {
				"2xs": "var(--2xs)",
				"xs": "var(--xs)",
				"sm": "var(--sm)",
				"md": "var(--md)",
				"lg": "var(--lg)",
				"xl": "var(--xl)",
				"2xl": "var(--2xl)",
				"dropdown-offset": "var(---dropdown-offset)",
			},
			gap: {
				"badge": "var(--badge-gap)",
				"button": "var(--button-gap)",
				"callout": "var(--callout-gap)",
				"dropdown": "var(--dropdown-gap)",
				"option": "var(--dropdown-option-gap)",
				"input": "var(--input-gap)",
			},
			minWidth: {
				"2xs": "var(--2xs)",
				"xs": "var(--xs)",
				"sm": "var(--sm)",
				"md": "var(--md)",
				"lg": "var(--lg)",
				"xl": "var(--xl)",
				"2xl": "var(--2xl)",
				"article": "var(--article-width)",
				"button": "var(--button-gap)",
				"dropdown": "var(--dropdown-min-width)",
			},
			width: {
				"article": "var(--article-width)",
				"button": "var(--button-height)",
				"button-mobile": "var(--button-height-mobile)",
				"input": "var(--input-height)",
				"input-mobile": "var(--input-height-mobile)",
				"modal": "var(--modal-width)",
				"page": "var(--page-width)",
			},
			maxWidth: {
				"2xs": "var(--2xs)",
				"xs": "var(--xs)",
				"sm": "var(--sm)",
				"md": "var(--md)",
				"lg": "var(--lg)",
				"xl": "var(--xl)",
				"2xl": "var(--2xl)",
				"article": "var(--article-width)",
				"tooltip": "var(--tooltip-max-width)",
			},
			minHeight: {
				"2xs": "var(--2xs)",
				"xs": "var(--xs)",
				"sm": "var(--sm)",
				"md": "var(--md)",
				"lg": "var(--lg)",
				"xl": "var(--xl)",
				"2xl": "var(--2xl)",
				"modal": "var(--modal-min-height)",
				"textarea": "var(--textarea-min-height)",
				"button": "var(--button-height)",
				"button-mobile": "var(--button-height-mobile)",
				"input": "var(--input-height)",
				"input-mobile": "var(--input-height-mobile)",
				"floating": "var(--input-floating-height)",
				"option": "var(--dropdown-option-height)",
				"switch": "var(--switch-height)",
			},
			height: {
				"button": "var(--button-height)",
				"button-mobile": "var(--button-height-mobile)",
				"input": "var(--input-height)",
				"input-mobile": "var(--input-height-mobile)",
				"floating": "var(--input-floating-height)",
				"option": "var(--dropdown-option-height)",
				"switch": "var(--switch-height)",
			},
			maxHeight: {
				"2xs": "var(--2xs)",
				"xs": "var(--xs)",
				"sm": "var(--sm)",
				"md": "var(--md)",
				"lg": "var(--lg)",
				"xl": "var(--xl)",
				"2xl": "var(--2xl)",
				"button": "var(--button-height)",
				"button-mobile": "var(--button-height-mobile)",
				"input": "var(--input-height)",
				"input-mobile": "var(--input-height-mobile)",
				"floating": "var(--input-floating-height)",
				"option": "var(--dropdown-option-height)",
				"switch": "var(--switch-height)",
			},
			margin: {
				"dropdown-divider": "var(--dropdown-divider-space)",
				"page": "var(--page-margin)",
			},
			padding: {
				"badge-x": "var(--badge-padding-x)",
				"badge-y": "var(--badge-padding-y)",
				"article": "var(--article-padding)",
				"button": "var(--button-padding)",
				"callout": "var(--button-padding)",
				"dropdown": "var(--dropdown-padding)",
				"option": "var(--dropdown-option-padding)",
				"input": "var(--input-padding)",
				"page": "var(--page-margin)",
			},
			scrollPadding: {
				"page": "var(--page-margin)",
			},
			scrollMargin: {
				"page": "var(--page-margin)",
			},
			zIndex: {
				"basic": "var(--stack-basic)",
				"subnav": "var(--stack-subnav)",
				"nav": "var(--stack-nav)",
				"toolbar": "var(--stack-toolbar)",
				"popover": "var(--stack-popover)",
				"dropdown": "var(--stack-dropdown)",
				"floating-button": "var(--stack-floating-button)",
				"backdrop": "var(--stack-backdrop)",
				"modal": "var(--stack-modal)",
				"toast": "var(--stack-toast)",
				"loading": "var(--stack-loading)",
			},
			fontFamily: {
				"a": "var(--a-font)",
				"badge": "var(--badge-font)",
				"button": "var(--button-font)",
				"callout": "var(--callout-font)",
				"caption": "var(--caption-font)",
				"code": "var(--code-font)",
				"divider": "var(--divider-font)",
				"h1": "var(--h1-font)",
				"h2": "var(--h2-font)",
				"h3": "var(--h3-font)",
				"h4": "var(--h4-font)",
				"h5": "var(--h5-font)",
				"h6": "var(--h6-weight)",
				"input": "var(--input-font)",
				"kbd": "var(--kbd-font)",
				"link": "var(--link-font)",
				"link-footer": "var(--link-footer-font)",
				"link-header": "var(--link-header-font)",
				"option": "var(--dropdown-option-font)",
				"p": "var(--p-font)",
				"pre": "var(--pre-font)",
				"quote": "var(--quote-font)",
				"small": "var(--small-font)",
				"table-header": "var(--table-header-font)",
				"table-cell": "var(--table-cell-font)",
				"tooltip": "var(--tooltip-font)",
			},
			fontWeight: {
				"a": "var(--a-weight)",
				"badge": "var(--badge-weight)",
				"button": "var(--button-weight)",
				"callout": "var(--callout-weight)",
				"caption": "var(--caption-weight)",
				"code": "var(--code-weight)",
				"divider": "var(--divider-weight)",
				"h1": "var(--h1-weight)",
				"h2": "var(--h2-weight)",
				"h3": "var(--h3-weight)",
				"h4": "var(--h4-weight)",
				"h5": "var(--h5-weight)",
				"h6": "var(--h6-weight)",
				"input": "var(--input-weight)",
				"kbd": "var(--kbd-weight)",
				"link": "var(--link-weight)",
				"link-footer": "var(--link-footer-weight)",
				"link-header": "var(--link-header-weight)",
				"option": "var(--dropdown-option-weight)",
				"p": "var(--p-weight)",
				"pre": "var(--pre-weight)",
				"quote": "var(--quote-weight)",
				"small": "var(--small-weight)",
				"table-header": "var(--table-header-weight)",
				"table-cell": "var(--table-cell-weight)",
				"tooltip": "var(--tooltip-weight)",
			},
			fontStyle: {
				"a": "var(--a-style)",
				"badge": "var(--badge-style)",
				"button": "var(--button-style)",
				"callout": "var(--callout-style)",
				"caption": "var(--caption-style)",
				"code": "var(--code-style)",
				"divider": "var(--divider-style)",
				"h1": "var(--h1-style)",
				"h2": "var(--h2-style)",
				"h3": "var(--h3-style)",
				"h4": "var(--h4-style)",
				"h5": "var(--h5-style)",
				"h6": "var(--h6-style)",
				"input": "var(--input-style)",
				"kbd": "var(--kbd-style)",
				"link": "var(--link-style)",
				"link-footer": "var(--link-footer-style)",
				"link-header": "var(--link-header-style)",
				"option": "var(--dropdown-option-style)",
				"p": "var(--p-style)",
				"pre": "var(--pre-style)",
				"quote": "var(--quote-style)",
				"small": "var(--small-style)",
				"table-header": "var(--table-header-style)",
				"table-cell": "var(--table-cell-style)",
				"tooltip": "var(--tooltip-style)",
			},
			fontSize: {
				"a": "var(--a-size)",
				"badge": "var(--badge-size)",
				"button": "var(--button-size)",
				"button-inline-icon": "var(--button-inline-icon-size)",
				"button-solo-icon": "var(--button-solo-icon-size)",
				"callout": "var(--callout-size)",
				"caption": "var(--caption-size)",
				"code": "var(--code-size)",
				"divider": "var(--divider-size)",
				"h1": "var(--h1-size)",
				"h2": "var(--h2-size)",
				"h3": "var(--h3-size)",
				"h4": "var(--h4-size)",
				"h5": "var(--h5-size)",
				"h6": "var(--h6-size)",
				"input": "var(--input-size)",
				"input-icon": "var(--input-icon-size)",
				"kbd": "var(--kbd-stysizele)",
				"link": "var(--link-style)",
				"link-footer": "var(--link-footer-size)",
				"link-header": "var(--link-header-size)",
				"option": "var(--dropdown-option-size)",
				"option-icon": "var(--dropdown-option-icon-size)",
				"p": "var(--p-size)",
				"pre": "var(--pre-size)",
				"quote": "var(--quote-size)",
				"small": "var(--small-size)",
				"table-header": "var(--table-header-size)",
				"table-cell": "var(--table-cell-size)",
				"tooltip": "var(--tooltip-size)",
			},
			lineHeight: {
				"badge": "var(--badge-leading)",
				"button": "var(--button-height)",
				"input": "var(--input-height)",
				"tooltip": "var(--tooltip-leading)",
			},
			letterSpacing: {
				"tootlip": "var(--tooltip-kerning)",
			},
			textColor: {
				"callout": "hsl(var(--callout-text) / <alpha-value>)",
				"chip": "hsl(var(--chip-text) / <alpha-value>)",
				"danger": "hsl(var(--danger-text) / <alpha-value>)",
				"placeholder": "hsl(var(--input-placeholder) / <alpha-value>)",
				"value": "hsl(var(--input-value) / <alpha-value>)",
				"primary": "hsl(var(--primary-text) / <alpha-value>)",
				"secondary": "hsl(var(--secondary-text) / <alpha-value>)",
			},
			borderRadius: {
				"2xs": "var(--2xs)",
				"xs": "var(--xs)",
				"sm": "var(--sm)",
				"md": "var(--md)",
				"lg": "var(--lg)",
				"xl": "var(--xl)",
				"2xl": "var(--2xl)",
				"badge": "var(--badge-radius)",
				"button": "var(--button-radius)",
				"dropdown": "var(--dropdown-radius)",
				"image": "var(--image-radius)",
				"input": "var(--input-radius)",
				"modal": "var(--modal-radius)",
				"switch": "var(--switch-radius)",
				"tooltip": "var(--tooltip-radius)",
				"video": "var(--video-radius)",
			},
			border: {
				"badge": "var(--badge-border)",
				"button-border": "hsl(var(--button-border) / <alpha-value>)",
				"button-border-hover": "hsl(var(--button-border-hover) / <alpha-value>)",
				"button-border-focus": "hsl(var(--button-border-focus) / <alpha-value>)",
				"input-border": "hsl(var(--input-border) / <alpha-value>)",
				"input-border-hover": "hsl(var(--input-border-hover) / <alpha-value>)",
				"input-border-focus": "hsl(var(--input-border-focus) / <alpha-value>)",
				"switch-border": "hsl(var(--switch-border) / <alpha-value>)",
				"switch-border-hover": "hsl(var(--switch-border-hover) / <alpha-value>)",
				"switch-border-focus": "hsl(var(--switch-border-focus) / <alpha-value>)",
			},
			borderWidth: {
				"badge": "var(--badge-border-width)",
				"button": "var(--button-border-width)",
				"dropdown": "var(--dropdown-border-width)",
				"input": "var(--input-border-width)",
				"input-bottom": "var(--input-border-bottom-width)",
				"switch": "var(--switch-border-width)",
			},
			outline: {
				"focus": "var(--focus-outline)",
			},
			outlineWidth: {
				"focus-width": "var(--focus-outline-width)",
			},
			outlineOffset: {
				"focus-offset": "var(--focus-outline-offset)",
			},
			boxShadow: {
				"badge": "var(--badge-shadow)",
				"button": "var(--button-shadow)",
				"dropdown": "var(--dropdown-shadow)",
				"image": "var(--image-shadow)",
				"input": "var(--input-shadow)",
				"modal": "var(--modal-shadow)",
				"switch": "var(--switch-shadow)",
				"tooltip": "var(--tooltip-shadow)",
				"video": "var(--video-shadow)",
			},
			dropShadow: {
				"badge": "var(--badge-shadow)",
				"button": "var(--button-shadow)",
				"dropdown": "var(--dropdown-shadow)",
				"image": "var(--image-shadow)",
				"input": "var(--input-shadow)",
				"modal": "var(--modal-shadow)",
				"switch": "var(--switch-shadow)",
				"tooltip": "var(--tooltip-shadow)",
				"video": "var(--video-shadow)",
			},
			cursor: {
				"button": "var(--button-cursor)",
				"input": "var(--input-cursor)",
				"option": "var(--dropdown-option-cursor)",
				"switch": "var(--switch-cursor)",
			},
			opacity: {
				"disabled": "var(--disabled-opacity)",
			},
			animation: {
				"background": 'background ease infinite',
			},
			keyframes: {
				"background": {
				  '0%, 100%': { backgroundPosition: '0% 50%' },
				  '50%': { backgroundPosition: '100% 50%' },
				}
			},
			screens: {
				"page": "var(--page-width)",
			},
		},
	},
	plugins: [
    	plugin(function siblingVariants({
			addVariant,
			e
		}) {
			// Adjacent sibling combinator
			addVariant("sibling", "& + *");
			// General sibling combinator
			addVariant("siblings", "& ~ *");
		}),
  	],
};

if (typeof module !== "undefined" && module.exports) {
	module.exports = tailwind.config;
}
