let tailwind;
try {
	tailwind = require("tailwindcss");
} catch (_) {
	tailwind = window.tailwind || {};
}

const plugin = tailwind.plugin;

tailwind.config = {
	darkMode: ['class'],
	theme: {
		extend: {
			colors: {
				"1": "color-mix(in srgb, var(--bg1) calc(<alpha-value> * 100%), transparent)",
				"2": "color-mix(in srgb, var(--bg2) calc(<alpha-value> * 100%), transparent)",
				"3": "color-mix(in srgb, var(--bg3) calc(<alpha-value> * 100%), transparent)",
				"4": "color-mix(in srgb, var(--bg4) calc(<alpha-value> * 100%), transparent)",
				"a": "color-mix(in srgb, var(--a) calc(<alpha-value> * 100%), transparent)",
				"a-hover": "color-mix(in srgb, var(--a-hover) calc(<alpha-value> * 100%), transparent)",
				"a-decoration": "color-mix(in srgb, var(--a-decoration) calc(<alpha-value> * 100%), transparent)",
				"a-decoration-hover": "color-mix(in srgb, var(--a-decoration-hover) calc(<alpha-value> * 100%), transparent)",
				"bold": "color-mix(in srgb, var(--bold) calc(<alpha-value> * 100%), transparent)",
				"backdrop": "color-mix(in srgb, var(--backdrop) calc(<alpha-value> * 100%), transparent)",
				"bullet": "color-mix(in srgb, var(--list-bullet) calc(<alpha-value> * 100%), transparent)",
				"button": "color-mix(in srgb, var(--button) calc(<alpha-value> * 100%), transparent)",
				"button-hover": "color-mix(in srgb, var(--button-hover) calc(<alpha-value> * 100%), transparent)",
				"button-focus": "color-mix(in srgb, var(--button-focus) calc(<alpha-value> * 100%), transparent)",
				"button-inverse": "color-mix(in srgb, var(--button-inverse) calc(<alpha-value> * 100%), transparent)",
				"button-inverse-hover": "color-mix(in srgb, var(--button-inverse-hover) calc(<alpha-value> * 100%), transparent)",
				"button-inverse-focus": "color-mix(in srgb, var(--button-inverse-focus) calc(<alpha-value> * 100%), transparent)",
				"button-border": "color-mix(in srgb, var(--button-border) calc(<alpha-value> * 100%), transparent)",
				"button-border-hover": "color-mix(in srgb, var(--button-border-hover) calc(<alpha-value> * 100%), transparent)",
				"button-border-focus": "color-mix(in srgb, var(--button-border-focus) calc(<alpha-value> * 100%), transparent)",
				"callout-bg": "color-mix(in srgb, var(--callout-bg) calc(<alpha-value> * 100%), transparent)",
				"callout-border": "color-mix(in srgb, var(--callout-border) calc(<alpha-value> * 100%), transparent)",
				"callout-text": "color-mix(in srgb, var(--callout-text) calc(<alpha-value> * 100%), transparent)",
				"caption": "color-mix(in srgb, var(--caption) calc(<alpha-value> * 100%), transparent)",
				"card-bg": "color-mix(in srgb, var(--card-bg) calc(<alpha-value> * 100%), transparent)",
				"card-border": "color-mix(in srgb, var(--card-border) calc(<alpha-value> * 100%), transparent)",
				"chip": "color-mix(in srgb, var(--chip) calc(<alpha-value> * 100%), transparent)",
				"chip-text": "color-mix(in srgb, var(--chip-text) calc(<alpha-value> * 100%), transparent)",
				"code-bg": "color-mix(in srgb, var(--code-bg) calc(<alpha-value> * 100%), transparent)",
				"code-border": "color-mix(in srgb, var(--code-border) calc(<alpha-value> * 100%), transparent)",
				"code-text": "color-mix(in srgb, var(--code-text) calc(<alpha-value> * 100%), transparent)",
				"contrast": "color-mix(in srgb, var(--contrast) calc(<alpha-value> * 100%), transparent)",
				"contrast-hover": "color-mix(in srgb, var(--contrast-hover) calc(<alpha-value> * 100%), transparent)",
				"contrast-focus": "color-mix(in srgb, var(--contrast-focus) calc(<alpha-value> * 100%), transparent)",
				"contrast-inverse": "color-mix(in srgb, var(--contrast-inverse) calc(<alpha-value> * 100%), transparent)",
				"contrast-inverse-hover": "color-mix(in srgb, var(--contrast-inverse-hover) calc(<alpha-value> * 100%), transparent)",
				"contrast-inverse-focus": "color-mix(in srgb, var(--contrast-inverse-focus) calc(<alpha-value> * 100%), transparent)",
				"contrast-text": "color-mix(in srgb, var(--contrast-text) calc(<alpha-value> * 100%), transparent)",
				"counter": "color-mix(in srgb, var(--list-counter) calc(<alpha-value> * 100%), transparent)",
				"danger": "color-mix(in srgb, var(--danger) calc(<alpha-value> * 100%), transparent)",
				"danger-hover": "color-mix(in srgb, var(--danger-hover) calc(<alpha-value> * 100%), transparent)",
				"danger-focus": "color-mix(in srgb, var(--danger-focus) calc(<alpha-value> * 100%), transparent)",
				"danger-inverse": "color-mix(in srgb, var(--danger-inverse) calc(<alpha-value> * 100%), transparent)",
				"danger-inverse-hover": "color-mix(in srgb, var(--danger-inverse-hover) calc(<alpha-value> * 100%), transparent)",
				"danger-inverse-focus": "color-mix(in srgb, var(--danger-inverse-focus) calc(<alpha-value> * 100%), transparent)",
				"danger-text": "color-mix(in srgb, var(--danger-text) calc(<alpha-value> * 100%), transparent)",
				"divider": "color-mix(in srgb, var(--divider) calc(<alpha-value> * 100%), transparent)",
				"divider-text": "color-mix(in srgb, var(--divider-text) calc(<alpha-value> * 100%), transparent)",
				"dropdown": "color-mix(in srgb, var(--dropdown) calc(<alpha-value> * 100%), transparent)",
				"dropdown-border": "color-mix(in srgb, var(--dropdown-border) calc(<alpha-value> * 100%), transparent)",
				"dropdown-divider": "color-mix(in srgb, var(--dropdown-divider) calc(<alpha-value> * 100%), transparent)",
				"dropdown-option-hover": "color-mix(in srgb, var(--dropdown-option-hover) calc(<alpha-value> * 100%), transparent)",
				"dropdown-option-focus": "color-mix(in srgb, var(--dropdown-option-focus) calc(<alpha-value> * 100%), transparent)",
				"dropdown-option-group": "color-mix(in srgb, var(--dropdown-option-group) calc(<alpha-value> * 100%), transparent)",
				"dropdown-option-text": "color-mix(in srgb, var(--dropdown-option-text) calc(<alpha-value> * 100%), transparent)",
				"dropdown-option-text-hover": "color-mix(in srgb, var(--dropdown-option-text-hover) calc(<alpha-value> * 100%), transparent)",
				"dropdown-option-text-focus": "color-mix(in srgb, var(--dropdown-option-text-focus) calc(<alpha-value> * 100%), transparent)",
				"dropdown-option-trailing-symbol": "color-mix(in srgb, var(--dropdown-option-trailing-symbol) calc(<alpha-value> * 100%), transparent)",
				"focus-outline": "color-mix(in srgb, var(--focus-outline) calc(<alpha-value> * 100%), transparent)",
				"h1": "color-mix(in srgb, var(--h1) calc(<alpha-value> * 100%), transparent)",
				"h2": "color-mix(in srgb, var(--h2) calc(<alpha-value> * 100%), transparent)",
				"h3": "color-mix(in srgb, var(--h3) calc(<alpha-value> * 100%), transparent)",
				"h4": "color-mix(in srgb, var(--h4) calc(<alpha-value> * 100%), transparent)",
				"h5": "color-mix(in srgb, var(--h5) calc(<alpha-value> * 100%), transparent)",
				"h6": "color-mix(in srgb, var(--h6) calc(<alpha-value> * 100%), transparent)",
				"input": "color-mix(in srgb, var(--input) calc(<alpha-value> * 100%), transparent)",
				"input-border-hover": "color-mix(in srgb, var(--input-border-hover) calc(<alpha-value> * 100%), transparent)",
				"input-border-focus": "color-mix(in srgb, var(--input-border-focus) calc(<alpha-value> * 100%), transparent)",
				"input-hover": "color-mix(in srgb, var(--input-hover) calc(<alpha-value> * 100%), transparent)",
				"input-focus": "color-mix(in srgb, var(--input-focus) calc(<alpha-value> * 100%), transparent)",
				"input-placeholder": "color-mix(in srgb, var(--input-placeholder) calc(<alpha-value> * 100%), transparent)",
				"input-value": "color-mix(in srgb, var(--input-value) calc(<alpha-value> * 100%), transparent)",
				"kbd-bg": "color-mix(in srgb, var(--kbd-bg) calc(<alpha-value> * 100%), transparent)",
				"kbd-border": "color-mix(in srgb, var(--kbd-border) calc(<alpha-value> * 100%), transparent)",
				"kbd-text": "color-mix(in srgb, var(--kbd-text) calc(<alpha-value> * 100%), transparent)",
				"label": "color-mix(in srgb, var(--label) calc(<alpha-value> * 100%), transparent)",
				"link": "color-mix(in srgb, var(--link) calc(<alpha-value> * 100%), transparent)",
				"link-hover": "color-mix(in srgb, var(--link-hover) calc(<alpha-value> * 100%), transparent)",
				"link-decoration": "color-mix(in srgb, var(--link-decoration) calc(<alpha-value> * 100%), transparent)",
				"link-decoration-hover": "color-mix(in srgb, var(--link-decoration-hover) calc(<alpha-value> * 100%), transparent)",
				"link-footer": "color-mix(in srgb, var(--link-footer) calc(<alpha-value> * 100%), transparent)",
				"link-footer-hover": "color-mix(in srgb, var(--link-footer-hover) calc(<alpha-value> * 100%), transparent)",
				"link-footer-decoration": "color-mix(in srgb, var(--link-footer-decoration) calc(<alpha-value> * 100%), transparent)",
				"link-footer-decoration-hover": "color-mix(in srgb, var(--link-footer-decoration-hover) calc(<alpha-value> * 100%), transparent)",
				"link-header": "color-mix(in srgb, var(--link-header) calc(<alpha-value> * 100%), transparent)",
				"link-header-hover": "color-mix(in srgb, var(--link-header-hover) calc(<alpha-value> * 100%), transparent)",
				"link-header-decoration": "color-mix(in srgb, var(--link-header-decoration) calc(<alpha-value> * 100%), transparent)",
				"link-header-decoration-hover": "color-mix(in srgb, var(--link-header-decoration-hover) calc(<alpha-value> * 100%), transparent)",
				"modal": "color-mix(in srgb, var(--modal) calc(<alpha-value> * 100%), transparent)",
				"modal-divider": "color-mix(in srgb, var(--modal-divider) calc(<alpha-value> * 100%), transparent)",
				"paragraph": "color-mix(in srgb, var(--paragraph) calc(<alpha-value> * 100%), transparent)",
				"page": "color-mix(in srgb, var(--page) calc(<alpha-value> * 100%), transparent)",
				"pre-bg": "color-mix(in srgb, var(--pre-bg) calc(<alpha-value> * 100%), transparent)",
				"pre-border": "color-mix(in srgb, var(--pre-border) calc(<alpha-value> * 100%), transparent)",
				"pre-text": "color-mix(in srgb, var(--pre-text) calc(<alpha-value> * 100%), transparent)",
				"primary": "color-mix(in srgb, var(--primary) calc(<alpha-value> * 100%), transparent)",
				"primary-hover": "color-mix(in srgb, var(--primary-hover) calc(<alpha-value> * 100%), transparent)",
				"primary-focus": "color-mix(in srgb, var(--primary-focus) calc(<alpha-value> * 100%), transparent)",
				"primary-inverse": "color-mix(in srgb, var(--primary-inverse) calc(<alpha-value> * 100%), transparent)",
				"primary-inverse-hover": "color-mix(in srgb, var(--primary-inverse-hover) calc(<alpha-value> * 100%), transparent)",
				"primary-inverse-focus": "color-mix(in srgb, var(--primary-inverse-focus) calc(<alpha-value> * 100%), transparent)",
				"primary-text": "color-mix(in srgb, var(--primary-text) calc(<alpha-value> * 100%), transparent)",
				"quote": "color-mix(in srgb, var(--quote) calc(<alpha-value> * 100%), transparent)",
				"quote-border": "color-mix(in srgb, var(--quote-border) calc(<alpha-value> * 100%), transparent)",
				"secondary": "color-mix(in srgb, var(--secondary) calc(<alpha-value> * 100%), transparent)",
				"secondary-hover": "color-mix(in srgb, var(--secondary-hover) calc(<alpha-value> * 100%), transparent)",
				"secondary-focus": "color-mix(in srgb, var(--secondary-focus) calc(<alpha-value> * 100%), transparent)",
				"secondary-inverse": "color-mix(in srgb, var(--secondary-inverse) calc(<alpha-value> * 100%), transparent)",
				"secondary-inverse-hover": "color-mix(in srgb, var(--secondary-inverse-hover) calc(<alpha-value> * 100%), transparent)",
				"secondary-inverse-focus": "color-mix(in srgb, var(--secondary-inverse-focus) calc(<alpha-value> * 100%), transparent)",
				"secondary-text": "color-mix(in srgb, var(--secondary-text) calc(<alpha-value> * 100%), transparent)",
				"small": "color-mix(in srgb, var(--small) calc(<alpha-value> * 100%), transparent)",
				"switch-off": "color-mix(in srgb, var(--switch-off) calc(<alpha-value> * 100%), transparent)",
				"switch-off-hover": "color-mix(in srgb, var(--switch-off-hover) calc(<alpha-value> * 100%), transparent)",
				"switch-off-focus": "color-mix(in srgb, var(--switch-off-focus) calc(<alpha-value> * 100%), transparent)",
				"switch-on": "color-mix(in srgb, var(--switch-on) calc(<alpha-value> * 100%), transparent)",
				"switch-on-hover": "color-mix(in srgb, var(--switch-on-hover) calc(<alpha-value> * 100%), transparent)",
				"switch-on-focus": "color-mix(in srgb, var(--switch-on-focus) calc(<alpha-value> * 100%), transparent)",
				"switch-border": "color-mix(in srgb, var(--switch-border) calc(<alpha-value> * 100%), transparent)",
				"switch-border-hover": "color-mix(in srgb, var(--switch-border-hover) calc(<alpha-value> * 100%), transparent)",
				"switch-border-focus": "color-mix(in srgb, var(--switch-border-focus) calc(<alpha-value> * 100%), transparent)",
				"switch-marker-off": "color-mix(in srgb, var(--switch-marker-off) calc(<alpha-value> * 100%), transparent)",
				"switch-marker-off-hover": "color-mix(in srgb, var(--switch-marker-off-hover) calc(<alpha-value> * 100%), transparent)",
				"switch-marker-off-focus": "color-mix(in srgb, var(--switch-marker-off-focus) calc(<alpha-value> * 100%), transparent)",
				"switch-marker-on": "color-mix(in srgb, var(--switch-marker-on) calc(<alpha-value> * 100%), transparent)",
				"switch-marker-on-hover": "color-mix(in srgb, var(--switch-marker-on-hover) calc(<alpha-value> * 100%), transparent)",
				"switch-marker-on-focus": "color-mix(in srgb, var(--switch-marker-on-focus) calc(<alpha-value> * 100%), transparent)",
				"table": "color-mix(in srgb, var(--table) calc(<alpha-value> * 100%), transparent)",
				"table-header-text": "color-mix(in srgb, var(--table-header-text) calc(<alpha-value> * 100%), transparent)",
				"table-header-row": "color-mix(in srgb, var(--table-header-row) calc(<alpha-value> * 100%), transparent)",
				"table-header-divider": "color-mix(in srgb, var(--table-header-divider) calc(<alpha-value> * 100%), transparent)",
				"table-row-even": "color-mix(in srgb, var(--table-row-even) calc(<alpha-value> * 100%), transparent)",
				"table-row-odd": "color-mix(in srgb, var(--table-row-odd) calc(<alpha-value> * 100%), transparent)",
				"table-row-divider": "color-mix(in srgb, var(--table-row-divider) calc(<alpha-value> * 100%), transparent)",
				"table-text": "color-mix(in srgb, var(--table-text) calc(<alpha-value> * 100%), transparent)",
				"text-1": "color-mix(in srgb, var(--text1) calc(<alpha-value> * 100%), transparent)",
				"text-2": "color-mix(in srgb, var(--text2) calc(<alpha-value> * 100%), transparent)",
				"text-3": "color-mix(in srgb, var(--text3) calc(<alpha-value> * 100%), transparent)",
				"text-4": "color-mix(in srgb, var(--text4) calc(<alpha-value> * 100%), transparent)",
				"text-5": "color-mix(in srgb, var(--text5) calc(<alpha-value> * 100%), transparent)",
				"text-6": "color-mix(in srgb, var(--text6) calc(<alpha-value> * 100%), transparent)",
				"tooltip-bg": "color-mix(in srgb, var(--tooltip-bg) calc(<alpha-value> * 100%), transparent)",
				"tooltip-border": "color-mix(in srgb, var(--tooltip-border) calc(<alpha-value> * 100%), transparent)",
				"tooltip-text": "color-mix(in srgb, var(--tooltip-text) calc(<alpha-value> * 100%), transparent)",
			},
			spacing: {
				"2xs": "var(--2xs)",
				"xs": "var(--xs)",
				"sm": "var(--sm)",
				"md": "var(--md)",
				"lg": "var(--lg)",
				"xl": "var(--xl)",
				"2xl": "var(--2xl)",
				"dropdown-offset": "var(---dropdown-offset)",
				"label-offset": "var(---label-offset)",
			},
			gap: {
				"badge": "var(--badge-gap)",
				"button": "var(--button-gap)",
				"callout": "var(--callout-gap)",
				"dropdown": "var(--dropdown-gap)",
				"option": "var(--dropdown-option-gap)",
				"input": "var(--input-gap)",
			},
			minWidth: {
				"2xs": "var(--2xs)",
				"xs": "var(--xs)",
				"sm": "var(--sm)",
				"md": "var(--md)",
				"lg": "var(--lg)",
				"xl": "var(--xl)",
				"2xl": "var(--2xl)",
				"article": "var(--article-width)",
				"button": "var(--button-gap)",
				"dropdown": "var(--dropdown-min-width)",
			},
			width: {
				"article": "var(--article-width)",
				"button": "var(--button-height)",
				"button-mobile": "var(--button-height-mobile)",
				"input": "var(--input-height)",
				"input-mobile": "var(--input-height-mobile)",
				"modal": "var(--modal-width)",
				"page": "var(--page-width)",
			},
			maxWidth: {
				"2xs": "var(--2xs)",
				"xs": "var(--xs)",
				"sm": "var(--sm)",
				"md": "var(--md)",
				"lg": "var(--lg)",
				"xl": "var(--xl)",
				"2xl": "var(--2xl)",
				"article": "var(--article-width)",
				"tooltip": "var(--tooltip-max-width)",
			},
			minHeight: {
				"2xs": "var(--2xs)",
				"xs": "var(--xs)",
				"sm": "var(--sm)",
				"md": "var(--md)",
				"lg": "var(--lg)",
				"xl": "var(--xl)",
				"2xl": "var(--2xl)",
				"modal": "var(--modal-min-height)",
				"textarea": "var(--textarea-min-height)",
				"button": "var(--button-height)",
				"button-mobile": "var(--button-height-mobile)",
				"input": "var(--input-height)",
				"input-mobile": "var(--input-height-mobile)",
				"floating": "var(--input-floating-height)",
				"option": "var(--dropdown-option-height)",
				"switch": "var(--switch-height)",
			},
			height: {
				"button": "var(--button-height)",
				"button-mobile": "var(--button-height-mobile)",
				"input": "var(--input-height)",
				"input-mobile": "var(--input-height-mobile)",
				"floating": "var(--input-floating-height)",
				"option": "var(--dropdown-option-height)",
				"switch": "var(--switch-height)",
			},
			maxHeight: {
				"2xs": "var(--2xs)",
				"xs": "var(--xs)",
				"sm": "var(--sm)",
				"md": "var(--md)",
				"lg": "var(--lg)",
				"xl": "var(--xl)",
				"2xl": "var(--2xl)",
				"button": "var(--button-height)",
				"button-mobile": "var(--button-height-mobile)",
				"input": "var(--input-height)",
				"input-mobile": "var(--input-height-mobile)",
				"floating": "var(--input-floating-height)",
				"option": "var(--dropdown-option-height)",
				"switch": "var(--switch-height)",
			},
			margin: {
				"dropdown-divider": "var(--dropdown-divider-space)",
				"page": "var(--page-margin)",
			},
			padding: {
				"badge-x": "var(--badge-padding-x)",
				"badge-y": "var(--badge-padding-y)",
				"article": "var(--article-padding)",
				"button": "var(--button-padding)",
				"callout": "var(--button-padding)",
				"card": "var(--card-padding)",
				"dropdown": "var(--dropdown-padding-y) var(--dropdown-padding-x)",
				"dropdown-x": "var(--dropdown-padding-x)",
				"dropdown-y": "var(--dropdown-padding-y)",
				"option": "var(--dropdown-option-padding)",
				"input": "var(--input-padding)",
				"section": "var(--page-section-padding) var(--page-margin)",
				"section-y": "var(--page-section-padding)",
				"page": "var(--page-margin)",
			},
			scrollPadding: {
				"page": "var(--page-margin)",
			},
			scrollMargin: {
				"page": "var(--page-margin)",
			},
			zIndex: {
				"basic": "var(--stack-basic)",
				"subnav": "var(--stack-subnav)",
				"nav": "var(--stack-nav)",
				"toolbar": "var(--stack-toolbar)",
				"popover": "var(--stack-popover)",
				"dropdown": "var(--stack-dropdown)",
				"floating-button": "var(--stack-floating-button)",
				"backdrop": "var(--stack-backdrop)",
				"modal": "var(--stack-modal)",
				"toast": "var(--stack-toast)",
				"loading": "var(--stack-loading)",
			},
			fontFamily: {
				"a": "var(--a-font)",
				"badge": "var(--badge-font)",
				"button": "var(--button-font)",
				"callout": "var(--callout-font)",
				"caption": "var(--caption-font)",
				"code": "var(--code-font)",
				"divider": "var(--divider-font)",
				"h1": "var(--h1-font)",
				"h2": "var(--h2-font)",
				"h3": "var(--h3-font)",
				"h4": "var(--h4-font)",
				"h5": "var(--h5-font)",
				"h6": "var(--h6-weight)",
				"input": "var(--input-font)",
				"kbd": "var(--kbd-font)",
				"link": "var(--link-font)",
				"link-footer": "var(--link-footer-font)",
				"link-header": "var(--link-header-font)",
				"option": "var(--dropdown-option-font)",
				"paragraph": "var(--p-font)",
				"pre": "var(--pre-font)",
				"quote": "var(--quote-font)",
				"small": "var(--small-font)",
				"table-header": "var(--table-header-font)",
				"table-cell": "var(--table-cell-font)",
				"tooltip": "var(--tooltip-font)",
			},
			fontWeight: {
				"weight-a": "var(--a-weight)",
				"weight-badge": "var(--badge-weight)",
				"weight-button": "var(--button-weight)",
				"weight-callout": "var(--callout-weight)",
				"weight-caption": "var(--caption-weight)",
				"weight-code": "var(--code-weight)",
				"weight-divider": "var(--divider-weight)",
				"weight-h1": "var(--h1-weight)",
				"weight-h2": "var(--h2-weight)",
				"weight-h3": "var(--h3-weight)",
				"weight-h4": "var(--h4-weight)",
				"weight-h5": "var(--h5-weight)",
				"weight-h6": "var(--h6-weight)",
				"weight-input": "var(--input-weight)",
				"weight-kbd": "var(--kbd-weight)",
				"weight-link": "var(--link-weight)",
				"weight-link-footer": "var(--link-footer-weight)",
				"weight-link-header": "var(--link-header-weight)",
				"weight-option": "var(--dropdown-option-weight)",
				"weight-paragraph": "var(--p-weight)",
				"weight-pre": "var(--pre-weight)",
				"weight-quote": "var(--quote-weight)",
				"weight-small": "var(--small-weight)",
				"weight-table-header": "var(--table-header-weight)",
				"weight-table-cell": "var(--table-cell-weight)",
				"weight-tooltip": "var(--tooltip-weight)",
			},
			fontStyle: {
				"style-a": "var(--a-style)",
				"style-badge": "var(--badge-style)",
				"style-button": "var(--button-style)",
				"style-callout": "var(--callout-style)",
				"style-caption": "var(--caption-style)",
				"style-code": "var(--code-style)",
				"style-divider": "var(--divider-style)",
				"style-h1": "var(--h1-style)",
				"style-h2": "var(--h2-style)",
				"style-h3": "var(--h3-style)",
				"style-h4": "var(--h4-style)",
				"style-h5": "var(--h5-style)",
				"style-h6": "var(--h6-style)",
				"style-input": "var(--input-style)",
				"style-kbd": "var(--kbd-style)",
				"style-link": "var(--link-style)",
				"style-link-footer": "var(--link-footer-style)",
				"style-link-header": "var(--link-header-style)",
				"style-option": "var(--dropdown-option-style)",
				"style-paragraph": "var(--p-style)",
				"style-pre": "var(--pre-style)",
				"style-quote": "var(--quote-style)",
				"style-small": "var(--small-style)",
				"style-table-header": "var(--table-header-style)",
				"style-table-cell": "var(--table-cell-style)",
				"style-tooltip": "var(--tooltip-style)",
			},
			fontSize: {
				"size-button": "var(--button-size)",
				"size-badge": "var(--badge-size)",
				"size-button-inline-icon": "var(--button-inline-icon-size)",
				"size-button-solo-icon": "var(--button-solo-icon-size)",
				"size-callout": "var(--callout-size)",
				"size-caption": "var(--caption-size)",
				"size-code": "var(--code-size)",
				"size-divider": "var(--divider-size)",
				"size-h1": "var(--h1-size)",
				"size-h2": "var(--h2-size)",
				"size-h3": "var(--h3-size)",
				"size-h4": "var(--h4-size)",
				"size-h5": "var(--h5-size)",
				"size-h6": "var(--h6-size)",
				"size-input": "var(--input-size)",
				"size-input-icon": "var(--input-icon-size)",
				"size-kbd": "var(--kbd-size)",
				"size-link-size": "var(--link-size)",
				"size-link-footer": "var(--link-footer-size)",
				"size-link-header": "var(--link-header-size)",
				"size-option": "var(--dropdown-option-size)",
				"size-option-icon": "var(--dropdown-option-icon-size)",
				"size-paragraph": "var(--p-size)",
				"size-pre": "var(--pre-size)",
				"size-quote": "var(--quote-size)",
				"size-small": "var(--small-size)",
				"size-table-header": "var(--table-header-size)",
				"size-table-cell": "var(--table-cell-size)",
				"size-tooltip": "var(--tooltip-size)",
			},
			lineHeight: {
				"badge": "var(--badge-leading)",
				"button": "var(--button-height)",
				"input": "var(--input-height)",
				"tooltip": "var(--tooltip-leading)",
			},
			letterSpacing: {
				"tootlip": "var(--tooltip-kerning)",
			},
			textColor: {
				"1": "color-mix(in srgb, var(--text1) calc(<alpha-value> * 100%), transparent)",
				"2": "color-mix(in srgb, var(--text2) calc(<alpha-value> * 100%), transparent)",
				"3": "color-mix(in srgb, var(--text3) calc(<alpha-value> * 100%), transparent)",
				"4": "color-mix(in srgb, var(--text4) calc(<alpha-value> * 100%), transparent)",
				"5": "color-mix(in srgb, var(--text5) calc(<alpha-value> * 100%), transparent)",
				"6": "color-mix(in srgb, var(--text6) calc(<alpha-value> * 100%), transparent)",
				"color-a": "color-mix(in srgb, var(--a) calc(<alpha-value> * 100%), transparent)",
				"color-a-hover": "color-mix(in srgb, var(--a-hover) calc(<alpha-value> * 100%), transparent)",
				"color-badge": "color-mix(in srgb, var(--badge-text) calc(<alpha-value> * 100%), transparent)",
				"color-bold": "color-mix(in srgb, var(--bold) calc(<alpha-value> * 100%), transparent)",
				"color-bullet": "color-mix(in srgb, var(--list-bullet) calc(<alpha-value> * 100%), transparent)",
				"callout": "color-mix(in srgb, var(--callout-text) calc(<alpha-value> * 100%), transparent)",
				"color-chip": "color-mix(in srgb, var(--chip-text) calc(<alpha-value> * 100%), transparent)",
				"color-caption": "color-mix(in srgb, var(--caption) calc(<alpha-value> * 100%), transparent)",
				"color-code": "color-mix(in srgb, var(--code-text) calc(<alpha-value> * 100%), transparent)",
				"color-counter": "color-mix(in srgb, var(--list-counter) calc(<alpha-value> * 100%), transparent)",
				"color-divider": "color-mix(in srgb, var(--divider-text) calc(<alpha-value> * 100%), transparent)",
				"color-h1": "color-mix(in srgb, var(--h1) calc(<alpha-value> * 100%), transparent)",
				"color-h2": "color-mix(in srgb, var(--h2) calc(<alpha-value> * 100%), transparent)",
				"color-h3": "color-mix(in srgb, var(--h3) calc(<alpha-value> * 100%), transparent)",
				"color-h4": "color-mix(in srgb, var(--h4) calc(<alpha-value> * 100%), transparent)",
				"color-h5": "color-mix(in srgb, var(--h5) calc(<alpha-value> * 100%), transparent)",
				"color-h6": "color-mix(in srgb, var(--h6) calc(<alpha-value> * 100%), transparent)",
				"color-input-placeholder": "color-mix(in srgb, var(--input-placeholder) calc(<alpha-value> * 100%), transparent)",
				"color-input-value": "color-mix(in srgb, var(--input-value) calc(<alpha-value> * 100%), transparent)",
				"color-kbd": "color-mix(in srgb, var(--kbd-text) calc(<alpha-value> * 100%), transparent)",
				"color-label": "color-mix(in srgb, var(--label) calc(<alpha-value> * 100%), transparent)",
				"color-link": "color-mix(in srgb, var(--link) calc(<alpha-value> * 100%), transparent)",
				"color-link-hover": "color-mix(in srgb, var(--link-hover) calc(<alpha-value> * 100%), transparent)",
				"color-link-footer": "color-mix(in srgb, var(--link-footer) calc(<alpha-value> * 100%), transparent)",
				"color-link-footer-hover": "color-mix(in srgb, var(--link-footer-hover) calc(<alpha-value> * 100%), transparent)",
				"color-link-header": "color-mix(in srgb, var(--link-header) calc(<alpha-value> * 100%), transparent)",
				"color-link-header-hover": "color-mix(in srgb, var(--link-header-hover) calc(<alpha-value> * 100%), transparent)",
				"color-option": "color-mix(in srgb, var(--dropdown-option) calc(<alpha-value> * 100%), transparent)",
				"color-paragraph": "color-mix(in srgb, var(--paragraph) calc(<alpha-value> * 100%), transparent)",
				"color-pre": "color-mix(in srgb, var(--pre-text) calc(<alpha-value> * 100%), transparent)",
				"color-quote": "color-mix(in srgb, var(--quote) calc(<alpha-value> * 100%), transparent)",
				"color-small": "color-mix(in srgb, var(--small) calc(<alpha-value> * 100%), transparent)",
				"color-table-header": "color-mix(in srgb, var(--table-header-text) calc(<alpha-value> * 100%), transparent)",
				"color-table": "color-mix(in srgb, var(--table-text) calc(<alpha-value> * 100%), transparent)",
				"contrast": "color-mix(in srgb, var(--contrast-text) calc(<alpha-value> * 100%), transparent)",
				"danger": "color-mix(in srgb, var(--danger-text) calc(<alpha-value> * 100%), transparent)",
				"primary": "color-mix(in srgb, var(--primary-text) calc(<alpha-value> * 100%), transparent)",
				"secondary": "color-mix(in srgb, var(--secondary-text) calc(<alpha-value> * 100%), transparent)",
			},
			borderRadius: {
				"2xs": "var(--2xs)",
				"xs": "var(--xs)",
				"sm": "var(--sm)",
				"md": "var(--md)",
				"lg": "var(--lg)",
				"xl": "var(--xl)",
				"2xl": "var(--2xl)",
				"badge": "var(--badge-radius)",
				"button": "var(--button-radius)",
				"card": "var(--card-radius)",
				"dropdown": "var(--dropdown-radius)",
				"image": "var(--image-radius)",
				"input": "var(--input-radius)",
				"modal": "var(--modal-radius)",
				"option": "var(--dropdown-option-radius)",
				"switch": "var(--switch-radius)",
				"tooltip": "var(--tooltip-radius)",
				"video": "var(--video-radius)",
			},
			border: {
				"badge": "color-mix(in srgb, var(--badge-border) calc(<alpha-value> * 100%), transparent)",
				"button-border": "color-mix(in srgb, var(--button-border) calc(<alpha-value> * 100%), transparent)",
				"button-border-hover": "color-mix(in srgb, var(--button-border-hover) calc(<alpha-value> * 100%), transparent)",
				"button-border-focus": "color-mix(in srgb, var(--button-border-focus) calc(<alpha-value> * 100%), transparent)",
				"card-border": "color-mix(in srgb, var(--card-border) calc(<alpha-value> * 100%), transparent)",
				"input-border": "color-mix(in srgb, var(--input-border) calc(<alpha-value> * 100%), transparent)",
				"input-border-hover": "color-mix(in srgb, var(--input-border-hover) calc(<alpha-value> * 100%), transparent)",
				"input-border-focus": "color-mix(in srgb, var(--input-border-focus) calc(<alpha-value> * 100%), transparent)",
				"switch-border": "color-mix(in srgb, var(--switch-border) calc(<alpha-value> * 100%), transparent)",
				"switch-border-hover": "color-mix(in srgb, var(--switch-border-hover) calc(<alpha-value> * 100%), transparent)",
				"switch-border-focus": "color-mix(in srgb, var(--switch-border-focus) calc(<alpha-value> * 100%), transparent)",
			},
			borderWidth: {
				"badge": "var(--badge-border-width)",
				"button": "var(--button-border-width)",
				"card": "var(--card-border-width)",
				"dropdown": "var(--dropdown-border-width)",
				"input": "var(--input-border-width)",
				"input-bottom": "var(--input-border-bottom-width)",
				"switch": "var(--switch-border-width)",
			},
			outline: {
				"focus": "var(--focus-outline)",
			},
			outlineWidth: {
				"focus-width": "var(--focus-outline-width)",
			},
			outlineOffset: {
				"focus-offset": "var(--focus-outline-offset)",
			},
			boxShadow: {
				"badge": "var(--badge-shadow)",
				"button": "var(--button-shadow)",
				"card": "var(--card-shadow)",
				"dropdown": "var(--dropdown-shadow)",
				"image": "var(--image-shadow)",
				"input": "var(--input-shadow)",
				"modal": "var(--modal-shadow)",
				"switch": "var(--switch-shadow)",
				"tooltip": "var(--tooltip-shadow)",
				"video": "var(--video-shadow)",
			},
			dropShadow: {
				"badge": "var(--badge-shadow)",
				"button": "var(--button-shadow)",
				"card": "var(--card-shadow)",
				"dropdown": "var(--dropdown-shadow)",
				"image": "var(--image-shadow)",
				"input": "var(--input-shadow)",
				"modal": "var(--modal-shadow)",
				"switch": "var(--switch-shadow)",
				"tooltip": "var(--tooltip-shadow)",
				"video": "var(--video-shadow)",
			},
			cursor: {
				"button": "var(--button-cursor)",
				"input": "var(--input-cursor)",
				"option": "var(--dropdown-option-cursor)",
				"switch": "var(--switch-cursor)",
			},
			opacity: {
				"disabled": "var(--disabled-opacity)",
			},
			animation: {
				"background": 'background ease infinite',
			},
			keyframes: {
				"background": {
					'0%, 100%': { backgroundPosition: '0% 50%' },
					'50%': { backgroundPosition: '100% 50%' },
				}
			},
			screens: {
				"page": "var(--page-width)",
			},
		},
	},
	plugins: [
		plugin(function siblingVariants({
			addVariant,
			e
		}) {
			// Adjacent sibling combinator
			addVariant("sibling", "& + *");
			// General sibling combinator
			addVariant("siblings", "& ~ *");
		}),
	],
};

if (typeof module !== "undefined" && module.exports) {
	module.exports = tailwind.config;
}
